{% set name = "django-cms" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4ecc01c1540a0c96fa3183681cea7f5e07fd806b17a6b640c155c351b6271477

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=3.2,<5.0
    - django-classy-tags >=0.7.2
    - django-formtools >=2.1
    - django-treebeard >=4.3
    - django-sekizai >=0.7
    - djangocms-admin-style >=1.2
    - packaging
    - setuptools

test:
  imports:
    - cms
    - menus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.django-cms.org/
  summary: Lean enterprise content management powered by Django.
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - cms/static/cms/js/select2/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
