{% set name = "django-cms" %}
{% set version = "4.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4efa64e1fd5293666d00cb58c982d598bb902aea1b0a943ef7bce6b82063e1e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=2.2
    - django-classy-tags >=0.7.2
    - django-formtools >=2.1
    - django-treebeard >=4.3
    - django-sekizai >=0.7
    - djangocms-admin-style >=1.2
    - packaging
    - setuptools

test:
  imports:
    - cms
    - menus
  commands:
    - pip check
    - djangocms --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.django-cms.org/
  summary: Lean enterprise content management powered by Django.
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - cms/static/cms/js/select2/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
