# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 5.1.0

package:
  name: django-cms
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/django-cms/django_cms-${{ version }}.tar.gz
  sha256: fca369b7313fd5a2c838fc04df76d207b327cc615cc52e41ed62b6aaa40f012f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - django >=5.2
    - django-classy-tags >=0.7.2
    - django-formtools >=2.1
    - django-treebeard >=4.3
    - django-sekizai >=0.7
    - pyflakes
    - dj-database-url
tests:
  - python:
      imports:
        - cms
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  homepage: https://www.django-cms.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Lean enterprise content management powered by Django.
  description: |
    Lean enterprise content management powered by Django.
  repository: https://github.com/django-cms/django-cms
  documentation: https://docs.django-cms.org/

extra:
  recipe-maintainers:
    - rxm7706
